services:
    backend:
        build: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=
            - PORT=3000
            - DATABASE_URL=
            - JWT_SECRET=
            - JWT_EXPIRES_IN=
            - JWT_REFRESH_SECRET=
            - JWT_REFRESH_EXPIRES_IN=
